### ISSUE TITLE
Remove the ayylmaozedong file?

### ISSUE THREAD

**Issue by kasplat** [reuami2017/reuami2017-asl#1]
Remove it? Not sure if its being used or not.

**Comment by DanielTakeshi** [comment]
If you're referring to the file that's in the `__pycache__` folder, yes you don't need it. The `__pycache__` should be in `.gitignore` since it's a binary file generated from Python 3 when it runs code that uses a C backend.

**Comment by shareefalis** [comment]
issue resolved here https://github.com/reuami2017/reuami2017-asl/commit/e1ed14e4ec8f19b459ec4ee81f321318380c2f2d
